//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPPiJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorije
    {
        public Kategorije()
        {
            this.Pitanjas = new HashSet<Pitanja>();
            this.Rezultatis = new HashSet<Rezultati>();
        }
    
        public int KategorijaID { get; set; }
        public int PredmetID { get; set; }
        public string KategorijaName { get; set; }
    
        public virtual Predmeti Predmeti { get; set; }
        public virtual ICollection<Pitanja> Pitanjas { get; set; }
        public virtual ICollection<Rezultati> Rezultatis { get; set; }
    }
}
