//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPPiJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Pitanja
    {
        public int PitanjeID { get; set; }
        public int KategorijaID { get; set; }
        public short VrstaPitanja { get; set; }

        public string Pitanje { get; set; }

        [Display(Name = "Točan odgovor")]
        public string TocanOdgovor { get; set; }

        [Display(Name = "Krivi odgovor 1.")]
        public string KriviOdgovor { get; set; }

        [Display(Name = "Krivi odgovor 2.")]
        public string KriviOdgovor2 { get; set; }

        [Display(Name = "Krivi odgovor 3.")]
        public string KriviOdgovor3 { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual Kategorije Kategorije { get; set; }
        public virtual VrstaPitanja VrstaPitanja1 { get; set; }
    }
}
