//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPPiJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Rezultati
    {
        public int RezultatID { get; set; }

        [Display(Name = "Korisnik")]
        public int UserID { get; set; }

        [Display(Name = "Kategorija")]
        public int KategorijaID { get; set; }

        [Display(Name = "Najbolji rezultat")]
        public int NajboljiRezultat { get; set; }

        [Display(Name = "Zadnji rezultat")]
        public int ZadnjiRezultat { get; set; }
    
        public virtual Kategorije Kategorije { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
