//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPPiJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.OstvareniAchievementi = new HashSet<OstvareniAchievementi>();
            this.Rezultati = new HashSet<Rezultati>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool UserType { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<OstvareniAchievementi> OstvareniAchievementi { get; set; }
        public virtual ICollection<Rezultati> Rezultati { get; set; }
    }
}
