//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPPiJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.OstvareniAchievemntis = new HashSet<OstvareniAchievemnti>();
            this.Rezultatis = new HashSet<Rezultati>();
        }
       
        public int UserID { get; set; }

        [Required()]
        [Display(Name = "Korisničko ime")]
        public string Username { get; set; }

        [Required()]
        [Display(Name = "Lozinka")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required()]
        [Display(Name = "Ime")]
        public string Name { get; set; }

        [Required()]
        [Display(Name = "Prezime")]
        public string LastName { get; set; }

        [Required()]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public bool UserType { get; set; }
    
        public virtual ICollection<OstvareniAchievemnti> OstvareniAchievemntis { get; set; }
        public virtual ICollection<Rezultati> Rezultatis { get; set; }
    }
}
